### ISSUE TITLE
Raise an error when invalid move is selected

### ISSUE THREAD

**Issue by rahul-dev-app** [hsahovic/poke-env#104]
Hey, amazing work with the library! 

I have a question about Gen8EnvSinglePlayer class. In the _action_to_move function, if an illegal move requested a random move is implemented. Instead of implementing a random move, I want to raise a warning flag and retain the game state. Any thoughts on how I can implement that?

Thanks a lot in advance!

**Comment by hsahovic** [comment]
Hi @rahul-dev-app,

Thanks for opening this issue.
I think the way to go would be to modify the `_action_to_move` method to achieve what you want to do. In your case, that would just entail modifying the [last `else` branch](https://github.com/hsahovic/poke-env/blob/ed278982a6b2dab68a9eef6fe3b112ffbea4c946/src/poke_env/player/env_player.py#L507) in your player class - you can pretty much keep the rest of the method as is.

So:


```python
    def _action_to_move(  # pyre-ignore
        self, action: int, battle: Battle
    ) -> BattleOrder:
        if (
            action < 4
            and action < len(battle.available_moves)
            and not battle.force_switch
        ):
            return self.create_order(battle.available_moves[action])
        elif (
            not battle.force_switch
            and battle.can_z_move
            and battle.active_pokemon
            and 0
            <= action - 4
            < len(battle.active_pokemon.available_z_moves)  # pyre-ignore
        ):
            return self.create_order(
                battle.active_pokemon.available_z_moves[action - 4], z_move=True
            )
        elif (
            battle.can_mega_evolve
            and 0 <= action - 8 < len(battle.available_moves)
            and not battle.force_switch
        ):
            return self.create_order(battle.available_moves[action - 8], mega=True)
        elif (
            battle.can_dynamax
            and 0 <= action - 12 < len(battle.available_moves)
            and not battle.force_switch
        ):
            return self.create_order(battle.available_moves[action - 12], dynamax=True)
        elif 0 <= action - 16 < len(battle.available_switches):
            return self.create_order(battle.available_switches[action - 16])
        else:
            # Your logic
            raise ValueError(f"Invalid move selected in {battle.battle_tag}.\nState embedding:\n{self.embed(battle)}")
```

**Comment by rahul-dev-app** [comment]
Hey @hsahovic! Thanks for the prompt response!

Yes, I was looking at modifying the else condition for the `_action_to_move function`. Wouldn't `raise ValueError()` raise an error and stop the battle at that state? I want the battle to continue ensuring we make a legal move not a random one. How can I do that?

Sorry if I was not being specific earlier about what I wanted and I really appreciate you helping me out with this implementation.

Thanks again!

**Comment by hsahovic** [comment]
Yes, raising an error would stop the battle (or rather, leave it hanging until the process is closed).

`choose_random_move` should always return a legal move - that's why it's used here in the first place. If you want to choose something smarter if the returned action is illegal, you can either:
- use a built-in `Player`'s choose move function (eg. `return poke_env.player.baselines.SimpleHeuristicsPlayer.choose_move(self, battle)` 
- create your own logic, as [illustrated here](https://poke-env.readthedocs.io/en/stable/max_damage_player.html#creating-a-player)

That being said, using a smart tactic if the chosen move is illegal might backfire, as your agent might very well to return an illegal move in order to trigger the smarter move selection process.
