### ISSUE TITLE
toxic status counter

### ISSUE THREAD

**Issue by mancho2000** [hsahovic/poke-env#152]
Hey,

It seems to me that the status counter for toxic was off, so I added a reset to the counter under def _switch_in(self, details=None)
and I think solved the problem. Let me know if this is correct :)

**Comment by mancho2000** [comment]
Also, is there a way to obtain the weather and fields duration left?

**Comment by hsahovic** [comment]
Hey @mancho2000,

Thanks for bringing that up, it's a great catch! The main issue should be fixed by #153 

For fields and weather, `Battle.fields` maps `Field` objects to `int`s corresponding to the start turn of the field.
You can therefore do `{field: (battle.turn - start_turn) for field, turn in battle.fields.items}` to get a map from active `Field`s to the number of turns a `Field` has been active. `Battle.weather` works the same way. To get remaining turns, you'll need to take context into account - for weather, you'll know it's either `5 - number_of_active_turns` or `8 - number_of_active_turns`, depending on held items, for instance :)
