### ISSUE TITLE
Learning from replays 

### ISSUE THREAD

**Issue by mancho1987** [hsahovic/poke-env#47]
Hey! This is amazing, thanks for what you are doing :) 
I was wondering if you have considered adding an agent that has been trained on replays from great players, or implementing a tool to help us do it ourselves. It could be used as an opponent for our self-play trained agents, or also could be trained further with self-play (as was done for Alphastar if I am not mistaken)

**Comment by hsahovic** [comment]
Hi @mancho1987!

Thanks for opening this issue.
Right now, there is no specific utility designed to learn from external battle replays. However, if you have access to a sufficiently large set of showdown replays, you could use the logs to _simulate_ a battle directly in `poke-env` with minimal code changes, and train a model based on that.

Basically, when `poke-env` receives a message from showdown, it is parsed and used via a private method in `Player` called `_handle_message` ([defined here](https://github.com/hsahovic/poke-env/blob/master/src/poke_env/player/player_network_interface.py#L117)). Instead of playing actual battles, you could inject whatever set of logs you have through this method and extract training data from it, the very same way you would by playing real battles: the rest of the training process would be exactly the same. You would probably also need to prevent actually sending orders, but that shouldn't be a problem.

A pseudo-code would probably look like this:
```
player = Player(...)

states = []
actions = []
rewards = []

for battle in battles_logs:
    for message in battles.messages:
        await player._handle_message(message)
        if requires_move(message):
            states.append(embed(Player))
            rewards.append(get_reward(Player.current_battle))
        if is_action(message)
            actions.append(action_from_message(message))
```

It would necessitate some custom code to work properly, but it's definitely doable with this framework :)

You could also implement a some of this logic by carefully crafting a weird `choose_move` method.

Let me know if this answers your question!

**Comment by mancho1987** [comment]
It does clarify things :) I will give it a go when I have a chance. Btw, have you trained any agents? How did they perform?

**Comment by hsahovic** [comment]
I have a couple agents performing a bit better than the example agents (something like ~75 wr against the example `MaxDamagePlayer`), but nothing much better than that for now. For the time being, I'm focusing on team building.

There are a couple of groups working on the question tho: some have public repo, for instance [this project](https://github.com/nicolenair/poke-env) or [this one](https://github.com/dem1995/pokemon-evolutionary-agents).
