### ISSUE TITLE
Extracting raw battle data during battle

### ISSUE THREAD

**Issue by BaiqingL** [hsahovic/poke-env#566]
Is it possible to extract the battle history during the middle of a battle? This scenario would help with prompting LLMs for context, and is it possible to do right now, thanks!

**Comment by caymansimpson** [comment]
You can do that through the `Observations` class, found [here](https://github.com/hsahovic/poke-env/blob/master/src/poke_env/environment/abstract_battle.py#L1017). They store the battle outputs in the `events` property: https://github.com/hsahovic/poke-env/blob/master/src/poke_env/environment/observation.py

**Comment by BaiqingL** [comment]
Thanks for the response @caymansimpson , however I noticed that the observations class don't store the event when a pokemon gets knocked out until the next turn, this makes sense since a knockout -> swap to new pokemon all happens in one turn.

However, when implementing the choose_move function, knowing what move knocked out the pokemon is also quite important for me. Is there a way to access what move happened before the knockout, like accessing half the turn data?

Thanks!

**Comment by caymansimpson** [comment]
Yes, an `observation` records the state of the turn at the beginning of the turn, and the `events` that happen during it. So it only gets added to the `battle.observations` Dict at the end of each turn. If you would like up-to-date battle information, feel free to use `battle._current_observation.events`; while it is an internal variable, it will have all the most recent `events` returned by the Showdown engine.

We can probably consider adding it as an "official" `AbstractBattle` property because I do think this use-case is legitimate. But using the above should suffice for your use-case for now.

**Comment by BaiqingL** [comment]
When I tried to print out each `battle._current_observation.events` during the choose_move function, it shows the events list as empty, a short snippet to reproduce:
```python
  def choose_move(self, battle: Battle) -> BattleOrder:


      # get raw battle history
      print(battle._current_observation)
```

**Comment by caymansimpson** [comment]
Ah I do see that it returns empty, and sorry for leading you astray! This is because the Player is prompted at the beginning of the turn before anything happens.

If in `choose_move`, you run
```
            if len(battle.observations.keys()) > 0:
                last_turn_recorded = max(battle.observations.keys())
                print(battle.observations[last_turn_recorded].events)
```

You will see the move that knocked out the mon in your previous turn. For example I see:
```
[['', ''], ['', 'switch', 'p2a: Smeargle', 'Smeargle, L50, F', '100/100'], ['', 'move', 'p1b: Raichu', 'Feint', 'p2b: Rillaboom'], ['', '-damage', 'p2b: Rillaboom', '20/100 par'], ['', 'move', 'p2b: Rillaboom', 'Trailblaze', 'p1a: Tyranitar'], ['', '-supereffective', 'p1a: Tyranitar'], ['', '-damage', 'p1a: Tyranitar', '0 fnt'], ['', '-boost', 'p2b: Rillaboom', 'spe', '1'], ['', 'faint', 'p1a: Tyranitar'], ['', ''], ['', '-weather', 'none'], ['', '-damage', 'p2a: Smeargle', '88/100', '[from] item: Black Sludge'], ['', '-heal', 'p1b: Raichu', '36/167', '[from] Grassy Terrain'], ['', '-heal', 'p2b: Rillaboom', '26/100 par', '[from] Grassy Terrain'], ['', '-fieldend', 'move: Grassy Terrain'], ['', '-ability', 'p2a: Smeargle', 'Moody', 'boost'], ['', '-boost', 'p2a: Smeargle', 'spd', '2'], ['', '-unboost', 'p2a: Smeargle', 'def', '1'], ['', 'upkeep'], ['', 'turn', '12']]
```
which shows that Tyranitar was KO'ed by Trailblaze in the previous turn?

If I add a pivot move, printing `battle._current_observation.events` also shows all the events leading up to that move in the current turn:
```[['', ''], ['', 'move', 'p1b: Smeargle', 'U-turn', 'p2a: Pelipper'], ['', '-resisted', 'p2a: Pelipper'], ['', '-damage', 'p2a: Pelipper', '75/100']]```
In this case, the first move in the turn was made by a Smeargle that used U-turn

This is all just to say that I think this is working as expected, and you should have everything you need?
